[package]
name = "action_demo"
version = "0.1.0"
authors = ["rmctJ <11417719+rmctJ@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
